### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MemeHoovy** [swordcube/FNF-Plasma-Engine#17]
source/states/PlayState.hx:626: characters 76-87 : Type not found : VideoSprite
I saw the readme but the repo for the hxCodec thing leads to a "page not found" though, so idk what to do.

**Comment by swordcube** [comment]
i deleted my repo for hxCodec because my changes got accepted, so normal git hxCodec can be used:
```haxelib git hxCodec https://github.com/polybiusproxy/hxCodec```

**Comment by MemeHoovy** [comment]
cool
